apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      postgres.service: postgres
  template:
    metadata:
      labels:
        postgres.service: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        ports:
        - name: postgres
          containerPort: {{ .Values.postgres.port }}
