apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      postgresql.service: postgresql
  template:
    metadata:
      labels:
        postgresql.service: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
             name: secret-postgresql
             key: postgresql-password
        - name: POSTGRES_USER
          value: {{ .Values.username | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database | quote }}
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresql-data
      volumes:
       - name: postgresql-data
         persistentVolumeClaim:
           claimName: pvc-hostpath