apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: "5432"
      port: {{ .Values.expose | default 5432 }}
      targetPort: {{ .Values.expose | default 5432 }}
  selector:
    postgresql.service: postgresql