apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: "port"
      port: {{ .Values.expose | default 5432 }}
      targetPort: {{ .Values.expose | default 5432 }}
{{ if .Values.expose }} 
  type: LoadBalancer
{{ end }}
  selector:
    postgresql.service: postgresql