apiVersion: v1
kind: Secret
metadata:
  name: secret-postgresql
type: Opaque
stringData:
  postgresql-password: 
    {{ if .Values.password }}
      {{ .Values.password  | quote }}
     {{ else }}
      {{ randAlphaNum 10  | quote }}
    {{ end }}