apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 
    {{ if .Values.postgresdatadir }}
      {{ .Values.postgresdatadir | quote }}
    {{ else }}
      {{ "" }}
    {{ end }}
