image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  
postgressql:
  username: postgres
  password: postgres
  database: postgres
  port: 5432
  
postgresdatadir: '/postgresdata'